// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
// / import 'firebase_options.dart';
// / // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
// / ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRGK0zUJilGvWnzWx0h_2o2LxS57fdRHQ',
    appId: '1:949122919399:web:5681ade462e64beeac6b42',
    messagingSenderId: '949122919399',
    projectId: 'uni-connect-a104f',
    authDomain: 'uni-connect-a104f.firebaseapp.com',
    storageBucket: 'uni-connect-a104f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYkiI8StFz_kM8Yzy1x5o0Hl4fYS_plz8',
    appId: '1:949122919399:android:beb45656ed9ab673ac6b42',
    messagingSenderId: '949122919399',
    projectId: 'uni-connect-a104f',
    storageBucket: 'uni-connect-a104f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOfk5UjGd1l9leS_4iqkO17I0WIYXR4uE',
    appId: '1:949122919399:ios:da2d1daae6c5a4dfac6b42',
    messagingSenderId: '949122919399',
    projectId: 'uni-connect-a104f',
    storageBucket: 'uni-connect-a104f.appspot.com',
    iosBundleId: 'com.example.uniConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOfk5UjGd1l9leS_4iqkO17I0WIYXR4uE',
    appId: '1:949122919399:ios:c7dd119b2a83af3fac6b42',
    messagingSenderId: '949122919399',
    projectId: 'uni-connect-a104f',
    storageBucket: 'uni-connect-a104f.appspot.com',
    iosBundleId: 'com.example.uniConnect.RunnerTests',
  );
}
